### ISSUE TITLE
Compilation warnings under Emacs 29.2

### ISSUE THREAD

**Issue by rdiez** [jscheid/dtrt-indent#79]
First of all, many thanks for dtrt-indent.

I just upgraded to Emacs 29.2 and dtrt-indent 1.16, and now I am getting these compilation warnings:

```
⛔ Warning (comp): dtrt-indent.el:198:44: Warning: reference to free variable ‘smie-grammar’
⛔ Warning (comp): dtrt-indent.el:200:25: Warning: reference to free variable ‘smie-config--buffer-local’
⛔ Warning (comp): dtrt-indent.el:201:19: Warning: reference to free variable ‘dtrt-indent-run-after-smie’
⛔ Warning (comp): dtrt-indent.el:207:31: Warning: defcustom for ‘dtrt-indent-global-mode’ fails to specify containing group
⛔ Warning (comp): dtrt-indent.el:207:2: Warning: docstring has wrong usage of unescaped single quotes (use \= or different quoting)
⛔ Warning (comp): dtrt-indent.el:437:2: Warning: custom-declare-variable `dtrt-indent-require-confirmation-flag' docstring has wrong usage of unescaped single quotes (use \= or different quoting)
⛔ Warning (comp): dtrt-indent.el:580:2: Warning: custom-declare-variable `dtrt-indent-min-matching-indentations' docstring has wrong usage of unescaped single quotes (use \= or different quoting)
⛔ Warning (comp): dtrt-indent.el:200:53: Warning: the function ‘smie-config-guess’ is not known to be defined.
```

**Comment by rrthomas** [comment]
Thanks for these. Patch welcome, otherwise I'll look at it some time.

**Comment by rrthomas** [comment]
Fixed. (One warning remains for me in Emacs 29.3, but it's incorrect, as it complains about a single quote character in a docstring, but the line in question is a comment, not a docstring.)

**Comment by rdiez** [comment]
Thanks for working on this.

I am still getting some warnings though:

```
In dtrt-indent-mode:
dtrt-indent.el:199:44: Warning: reference to free variable ‘smie-grammar’
dtrt-indent.el:201:25: Warning: reference to free variable
    ‘smie-config--buffer-local’

In end of data:
dtrt-indent.el:201:53: Warning: the function ‘smie-config-guess’ is not known
    to be defined.
```
Does dtrt-indent depend on a package called 'smie'?

**Comment by rrthomas** [comment]
It's an optional dependency, detected at runtime; see line 198. I wasn't sure what to do about this.

**Comment by rdiez** [comment]
I do not know much Lisp myself (I code in Elisp mainly via Google/copy/paste), but I have managed to silence such warnings in the past with 'eval-when-compile'. For example:

```
(defconst is-windows (eq system-type 'windows-nt))

(when (eval-when-compile is-windows)
  (require 'cygwin-mount)
  (cygwin-mount-activate)
)
```

One of the warnings left in dtrt-indent is "the function ‘smie-config-guess’ is not known to be defined", and the [documentation for related macro 'eval-and-compile'](https://www.gnu.org/software/emacs/manual/html_node/elisp/Eval-During-Compile.html) specifically mentions the suppression of such “not known to be defined” warnings.

**Comment by rrthomas** [comment]
The point of the code here is to detect whether the current mode is based on SMIE, so a better way to do that would be the correct solution, I think.

I think I could use `(boundp 'smie-grammar)` and `(boundp 'smie-config--buffer-local)` to suppress the warning, but it's starting to look rather hacky.

In general, I don't want to change working code in non-trivial ways just to fix warnings, though I do appreciate that it can be confusing to users who see the warnings. It's a shame there's no way to simply suppress the warning with some kind of pragma.

**Comment by rrthomas** [comment]
Does changing `(featurep 'smie)` to `(boundp 'smie-grammar)` fix one of the warnings, at least?

**Comment by rdiez** [comment]
> I do appreciate that it can be confusing to users who see the warnings

It also conveys a certain impression of neglect. I would at least add a comment at the warning locations, maybe with a reference to this GitHub issue, in order to mention that those warnings are known, so that the next guy around does not report it again.

> Does changing (featurep 'smie) to (boundp 'smie-grammar) fix one of the warnings, at least?

That does fix this warning:

dtrt-indent.el:199:44: Warning: reference to free variable ‘smie-grammar’

By the way, I reported the docstring warning here:

https://debbugs.gnu.org/cgi/bugreport.cgi?bug=75876

**Comment by rdiez** [comment]
The Emacs maintainer has commented about that warning, see here:
https://debbugs.gnu.org/cgi/bugreport.cgi?bug=75876

**Comment by rrthomas** [comment]
> The Emacs maintainer has commented about that warning, see here: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=75876

Many thanks for this, fixed, I think.

**Comment by rrthomas** [comment]
> It also conveys a certain impression of neglect.

It's unfortunate that the assumption these days is that if a package doesn't have frequent releases, or builds up warnings from linters, then it is somehow defective. Fixing lint warnings has a cost.

However, in this case we seem to have found some fairly clean fixes (though the docstring fix is only necessary because of a workaround in the dtrt code for a different Emacs bug :-/ ), so I'm not that unhappy.

I believe there should be two warnings left, for `smie-config-guess` and `smie-config--buffer-local`, correct?

**Comment by rdiez** [comment]
Yes, those are the remaining warnings:

```
In dtrt-indent-mode:
dtrt-indent.el:201:25: Warning: reference to free variable ‘smie-config--buffer-local’

In end of data:
dtrt-indent.el:201:53: Warning: the function ‘smie-config-guess’ is not known to be defined.
```

**Comment by rrthomas** [comment]
Thanks. I've committed a comment. Hopefully detecting SMIE will get less hacky in future.
